name: Start Docker Compose
on:
  workflow_dispatch:
  push:
    branches:
      - main-mjb
      - ssh-action
jobs:
  start-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and restart container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DO_SERVER_HOST_IP }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            cd /srv/mealie
            docker compose pull mealie
            docker compose up -d mealie
